# Generated by Django 4.1.3 on 2022-12-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
